
version: 2

sources:
    - name: staging
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: dtc-de-338616

      schema: taxirides

      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata      