
version: 2

sources:
    - name: staging
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: dtc-de-338616

      schema: taxi_data_ny

      tables:
        - name: green_tripdata
          identifier: green_tripdata_csv
          description: >          
              Green Cab Data.
        - name: yellow_tripdata
          identifier:  yellow_tripdata_csv
          description: >          
              Yellow Cab Data.
