
version: 2

sources:
    - name: staging
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: dtc-de-338616

      schema: taxi_data_ny

      tables:
        - name: green_tripdata_csv
        - name: yellow_tripdata_csv      